DROP TABLE IF EXISTS products, customers, departments, employees, orders CASCADE;

CREATE TABLE IF NOT EXISTS products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NOT NULL,
    available BOOLEAN
);

CREATE TABLE IF NOT EXISTS customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    telephone VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS departments (
    department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS employees (
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    patronymic VARCHAR(255) NOT NULL,
    department_id BIGINT NOT NULL REFERENCES departments(department_id)
);

CREATE TABLE IF NOT EXISTS orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    address VARCHAR(255) NOT NULL,
    comment VARCHAR(255),
    customer_id BIGINT NOT NULL REFERENCES customers(customer_id),
    employee_id BIGINT REFERENCES employees(employee_id),
    state VARCHAR(15)
);


